version: "3.8"

services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      tutorial_loadbalancer:
        ipv4_address: 10.0.1.1
    depends_on:
      - "app1"
      - "app2"

  app1:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: app1
    networks:
      tutorial_loadbalancer:
        ipv4_address: 10.0.1.2

  app2:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: app2
    networks:
      tutorial_loadbalancer:
        ipv4_address: 10.0.1.3

networks:
  tutorial_loadbalancer:
    name: tutorial_loadbalancer
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.1.0/24
